#!/bin/bash
#
#  COVID19d The COVID19 core server.
#
#
# chkconfig: 345 80 20
# description: COVID19d
# processname: COVID19d
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/COVID19d, see below
if [ -f /etc/sysconfig/COVID19d ]; then
        . /etc/sysconfig/COVID19d
fi

RETVAL=0

prog=COVID19d
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/COVID19d
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/COVID19d}

# COVID19d defaults to /usr/bin/COVID19d, override with BITCOIND_BIN
bitcoind=${BITCOIND_BIN-/usr/bin/COVID19d}

# COVID19d opts default to -disablewallet, override with BITCOIND_OPTS
bitcoind_opts=${BITCOIND_OPTS}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $bitcoind $bitcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
